trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml


resources:
- repo: self

variables:
  - name: dockerRegistryServiceConnection
    value: '7d7390acda764378c8dba3106bd2b1bf07e26567652a8fc7d014b69efc46337a'
  - name: imageRepository
    value: 'cosmopy'
  - name: containerRegistry
    value: 'cosmopy.azurecr.io'
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/cosmosdb-with-fastapi/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

stages:
- stage: BuildAndPushDockerImage
  displayName: Build and Push Docker image to Azure Container Registry
  jobs:
  - job: BuildAndpush
    displayName: Build
    pool:
      name: default
    steps:
    - task: AzureKeyVault@2
      displayName: Get secrets from Azure Key Vault
      inputs:
        azureSubscription: 'Personal (0b3d39cb-e454-4f00-a69c-df13d0bd46ad)'
        KeyVaultName: 'cosmokey'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: Docker@2
      displayName: Build the python image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'build'
        Dockerfile: $(dockerfilePath)
        tags: '$(tag)'
        arguments: '--build-arg DB_URI=$(uri) --build-arg DB_KEY=$(key) --build-arg INSIGHTS_KEY=$(insightskey)'
    
    - task: Docker@2
      displayName: Push Docker image to ACR
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'push'
    
- stage: DeployToContainerApp
  displayName: Deploy Dockerized Python Application To Azure Container Apps
  jobs:
  - job: Deploy
    displayName: Deploy Container App to Azure Web App for Container
    pool:
      name: default
    steps:
    - checkout: none
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Personal (0b3d39cb-e454-4f00-a69c-df13d0bd46ad)'
        appName: 'srimathiwebapp'
        multicontainerConfigFile: '$(Build.SourcesDirectory)/cosmosdb-with-fastapi/cosmo.yaml'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        publishLocation: 'pipeline'
